export const labSupplyBrands = {
  qualigens: {
    name: "Qualigens",
    description: "High-quality laboratory chemicals and reagents",
    category: "Laboratory Supplies",
    website: "https://qualigens.com",
    specialties: ["Analytical Reagents", "HPLC Solvents", "Buffer Solutions"],
  },
  borosil: {
    name: "Borosil",
    description: "Premium laboratory glassware and equipment",
    category: "Laboratory Supplies",
    website: "https://borosil.com",
    specialties: ["Glassware", "Laboratory Equipment", "Measuring Instruments"],
  },
  whatman: {
    name: "Whatman",
    description: "Filtration and separation products",
    category: "Laboratory Supplies",
    website: "https://whatman.com",
    specialties: ["Filter Papers", "Membrane Filters", "Separation Media"],
  },
  rankem: {
    name: "Rankem",
    description: "Laboratory chemicals and fine chemicals",
    category: "Laboratory Supplies",
    website: "https://rankem.com",
    specialties: ["Fine Chemicals", "Analytical Standards", "Custom Synthesis"],
  },
  jtbaker: {
    name: "J.T. Baker",
    description: "High-purity chemicals and solvents",
    category: "Laboratory Supplies",
    website: "https://jtbaker.com",
    specialties: ["HPLC Grade Solvents", "ACS Reagents", "Trace Analysis"],
  },
}

export const offers = [
  {
    id: 1,
    title: "Premium Lab Aprons - 30% Off",
    description: "High-quality chemical-resistant lab aprons. Limited time offer!",
    discount: "30% OFF",
    validUntil: "2024-03-31",
    image: "/images/offer-apron.png",
    brand: "Safety First",
    category: "Safety Equipment",
  },
  {
    id: 2,
    title: "Bulk Solvents - Special Pricing",
    description: "Get the best prices on bulk analytical grade solvents.",
    discount: "Up to 25% OFF",
    validUntil: "2024-04-15",
    image: "/images/offer-solvents.png",
    brand: "ChemPure",
    category: "Solvents",
  },
  {
    id: 3,
    title: "Free Shipping on Orders Above ₹50,000",
    description: "No shipping charges on bulk orders. Order now!",
    discount: "FREE SHIPPING",
    validUntil: "2024-05-01",
    image: "/images/offer-shipping.png",
    brand: "Chemical Corporation",
    category: "Shipping",
  },
  {
    id: 4,
    title: "Whatman Filter Papers - Buy 2 Get 1 Free",
    description: "Premium filter papers for all your laboratory needs.",
    discount: "Buy 2 Get 1 FREE",
    validUntil: "2024-04-30",
    image: "/images/offer-whatman-filters.png",
    brand: "Whatman",
    category: "Filtration",
  },
  {
    id: 5,
    title: "Borosil Glassware - 20% Off",
    description: "High-quality borosilicate glassware for laboratories.",
    discount: "20% OFF",
    validUntil: "2024-04-20",
    image: "/images/offer-borosil-glassware.png",
    brand: "Borosil",
    category: "Glassware",
  },
]

export const bulkChemicals = [
  {
    id: 1,
    name: "Sulfuric Acid (98%)",
    code: "SA-98-50L",
    description: "High purity sulfuric acid for industrial applications",
    packSize: "50L",
    price: "₹2,500",
    category: "Acids",
    purity: "98%",
    cas: "7664-93-9",
    hsn: "28070010",
  },
  {
    id: 2,
    name: "Hydrochloric Acid (37%)",
    code: "HCL-37-25L",
    description: "Analytical grade hydrochloric acid",
    packSize: "25L",
    price: "₹1,800",
    category: "Acids",
    purity: "37%",
    cas: "7647-01-0",
    hsn: "28061000",
  },
  {
    id: 3,
    name: "Sodium Hydroxide Pellets",
    code: "NAOH-P-25KG",
    description: "High purity sodium hydroxide pellets",
    packSize: "25kg",
    price: "₹3,200",
    category: "Bases",
    purity: "99%",
    cas: "1310-73-2",
    hsn: "28151100",
  },
  {
    id: 4,
    name: "Acetone (99.5%)",
    code: "ACE-995-20L",
    description: "HPLC grade acetone for analytical applications",
    packSize: "20L",
    price: "₹4,500",
    category: "Solvents",
    purity: "99.5%",
    cas: "67-64-1",
    hsn: "29141100",
  },
  {
    id: 5,
    name: "Methanol (99.9%)",
    code: "MEOH-999-25L",
    description: "Ultra-pure methanol for HPLC applications",
    packSize: "25L",
    price: "₹5,200",
    category: "Solvents",
    purity: "99.9%",
    cas: "67-56-1",
    hsn: "29051100",
  },
  {
    id: 6,
    name: "Sodium Chloride (99.5%)",
    code: "NACL-995-25KG",
    description: "High purity sodium chloride for laboratory use",
    packSize: "25kg",
    price: "₹1,200",
    category: "Salts",
    purity: "99.5%",
    cas: "7647-14-5",
    hsn: "25010010",
  },
]

export const labSupplies = [
  {
    id: 1,
    name: "Borosilicate Beakers Set",
    code: "BSB-SET-6",
    description: "Set of 6 borosilicate glass beakers (50ml to 1000ml)",
    packSize: "Set of 6",
    price: "₹2,800",
    category: "Glassware",
    brand: "Borosil",
    material: "Borosilicate Glass",
  },
  {
    id: 2,
    name: "Whatman Filter Paper Grade 1",
    code: "WFP-G1-100",
    description: "Qualitative filter paper for general filtration",
    packSize: "100 sheets",
    price: "₹450",
    category: "Filtration",
    brand: "Whatman",
    material: "Cellulose",
  },
  {
    id: 3,
    name: "Micropipette Set (0.5-10μL)",
    code: "MP-SET-010",
    description: "Variable volume micropipette with tips",
    packSize: "1 piece",
    price: "₹8,500",
    category: "Pipettes",
    brand: "Eppendorf",
    material: "Plastic/Metal",
  },
  {
    id: 4,
    name: "pH Buffer Solutions Set",
    code: "PBS-SET-3",
    description: "pH 4.0, 7.0, and 10.0 buffer solutions",
    packSize: "3 x 500ml",
    price: "₹1,200",
    category: "Reagents",
    brand: "Qualigens",
    material: "Aqueous Solution",
  },
  {
    id: 5,
    name: "Conical Flasks (250ml)",
    code: "CF-250-12",
    description: "Borosilicate conical flasks with narrow neck",
    packSize: "12 pieces",
    price: "₹1,800",
    category: "Glassware",
    brand: "Borosil",
    material: "Borosilicate Glass",
  },
  {
    id: 6,
    name: "Disposable Petri Dishes",
    code: "DPD-90-100",
    description: "Sterile disposable petri dishes 90mm diameter",
    packSize: "100 pieces",
    price: "₹650",
    category: "Plasticware",
    brand: "Tarsons",
    material: "Polystyrene",
  },
]

export const scientificInstruments = [
  {
    id: 1,
    name: "Digital pH Meter",
    code: "DPH-3000",
    description: "High precision digital pH meter with temperature compensation",
    packSize: "1 unit",
    price: "₹15,500",
    category: "pH Meters",
    brand: "Hanna Instruments",
    accuracy: "±0.01 pH",
  },
  {
    id: 2,
    name: "Analytical Balance (0.1mg)",
    code: "AB-220-4N",
    description: "4-decimal analytical balance with internal calibration",
    packSize: "1 unit",
    price: "₹85,000",
    category: "Balances",
    brand: "Sartorius",
    capacity: "220g",
  },
  {
    id: 3,
    name: "UV-Vis Spectrophotometer",
    code: "UVS-2600",
    description: "Double beam UV-Vis spectrophotometer with software",
    packSize: "1 unit",
    price: "₹3,50,000",
    category: "Spectrophotometers",
    brand: "Shimadzu",
    wavelength: "190-1100nm",
  },
  {
    id: 4,
    name: "Magnetic Stirrer with Hotplate",
    code: "MSH-300",
    description: "Digital magnetic stirrer with heating and temperature control",
    packSize: "1 unit",
    price: "₹12,500",
    category: "Stirrers",
    brand: "IKA",
    temperature: "Up to 300°C",
  },
  {
    id: 5,
    name: "Centrifuge (High Speed)",
    code: "CF-16RX",
    description: "Refrigerated high-speed centrifuge with rotor",
    packSize: "1 unit",
    price: "₹2,25,000",
    category: "Centrifuges",
    brand: "Thermo Scientific",
    speed: "16,000 RPM",
  },
  {
    id: 6,
    name: "Incubator (Bacteriological)",
    code: "INC-55L",
    description: "Bacteriological incubator with digital temperature control",
    packSize: "1 unit",
    price: "₹45,000",
    category: "Incubators",
    brand: "Labtech",
    capacity: "55 Liters",
  },
]
