export const commercialChemicals = [
  { code: "CC0001", name: "Acetic Acid Glacial", category: "Acids", pack_size: "500ml", price: "₹450" },
  { code: "CC0002", name: "Acetone", category: "Solvents", pack_size: "1L", price: "₹320" },
  { code: "CC0003", name: "Acetonitrile", category: "Solvents", pack_size: "1L", price: "₹850" },
  { code: "CC0004", name: "Alum (Non Ferric /Ferric)", category: "Salts", pack_size: "500g", price: "₹180" },
  { code: "CC0005", name: "Ammonium Bi Sulphite", category: "Salts", pack_size: "500g", price: "₹220" },
  { code: "CC0006", name: "Ammonium Chloride", category: "Salts", pack_size: "500g", price: "₹160" },
  { code: "CC0007", name: "Aniline", category: "Reagents", pack_size: "500ml", price: "₹380" },
  { code: "CC0008", name: "Benzene", category: "Solvents", pack_size: "500ml", price: "₹450" },
  { code: "CC0009", name: "Borox", category: "Salts", pack_size: "500g", price: "₹140" },
  { code: "CC0010", name: "Boric Acid Powder", category: "Acids", pack_size: "500g", price: "₹120" },
  { code: "CC0011", name: "Bleaching Powder", category: "Reagents", pack_size: "1kg", price: "₹80" },
  { code: "CC0012", name: "Butyl Acetate", category: "Solvents", pack_size: "1L", price: "₹420" },
  { code: "CC0013", name: "Butyl Cellosolve", category: "Solvents", pack_size: "1L", price: "₹480" },
  { code: "CC0014", name: "Butyl Alcohol", category: "Solvents", pack_size: "1L", price: "₹380" },
  { code: "CC0015", name: "Cab O Sil (Silicon Di Oxide)", category: "Reagents", pack_size: "500g", price: "₹650" },
  { code: "CC0016", name: "Calcium Chloride Lumps", category: "Salts", pack_size: "1kg", price: "₹120" },
  { code: "CC0017", name: "Caustic Potash Flakes", category: "Bases", pack_size: "500g", price: "₹280" },
  { code: "CC0018", name: "Caustic Soda Flakes", category: "Bases", pack_size: "500g", price: "₹180" },
  { code: "CC0019", name: "Citric Acid", category: "Acids", pack_size: "500g", price: "₹160" },
  { code: "CC0020", name: "Copper Sulphate", category: "Salts", pack_size: "500g", price: "₹220" },
  { code: "CC0021", name: "Cyclohexane", category: "Solvents", pack_size: "1L", price: "₹520" },
  { code: "CC0022", name: "Diethyl Ether", category: "Solvents", pack_size: "500ml", price: "₹960" },
  { code: "CC0023", name: "Dimethylformamide (DMF)", category: "Solvents", pack_size: "500ml", price: "₹670" },
  { code: "CC0024", name: "DMSO (Dimethyl Sulfoxide)", category: "Solvents", pack_size: "500ml", price: "₹780" },
  { code: "CC0025", name: "EDTA", category: "Reagents", pack_size: "100g", price: "₹450" },
  { code: "CC0026", name: "Ethyl Acetate", category: "Solvents", pack_size: "1L", price: "₹360" },
  { code: "CC0027", name: "Ethylene Glycol", category: "Solvents", pack_size: "500ml", price: "₹320" },
  { code: "CC0028", name: "Ferric Chloride", category: "Salts", pack_size: "500g", price: "₹240" },
  { code: "CC0029", name: "Formaldehyde", category: "Reagents", pack_size: "500ml", price: "₹150" },
  { code: "CC0030", name: "Formic Acid", category: "Acids", pack_size: "500ml", price: "₹370" },
  { code: "CC0031", name: "Glycerol (Glycerine)", category: "Reagents", pack_size: "500ml", price: "₹280" },
  { code: "CC0032", name: "Hexane", category: "Solvents", pack_size: "1L", price: "₹620" },
  { code: "CC0033", name: "Hydrochloric Acid", category: "Acids", pack_size: "500ml", price: "₹90" },
  { code: "CC0034", name: "Hydrogen Peroxide 30%", category: "Reagents", pack_size: "500ml", price: "₹110" },
  { code: "CC0035", name: "Iso Propyl Alcohol (IPA)", category: "Solvents", pack_size: "1L", price: "₹340" },
  { code: "CC0036", name: "Lactic Acid", category: "Acids", pack_size: "500ml", price: "₹450" },
  { code: "CC0037", name: "Magnesium Sulphate", category: "Salts", pack_size: "500g", price: "₹190" },
  { code: "CC0038", name: "Methanol", category: "Solvents", pack_size: "1L", price: "₹310" },
  { code: "CC0039", name: "Nitric Acid", category: "Acids", pack_size: "500ml", price: "₹150" },
  { code: "CC0040", name: "Oxalic Acid", category: "Acids", pack_size: "500g", price: "₹130" },
  { code: "CC0041", name: "Phenol Crystals", category: "Reagents", pack_size: "250g", price: "₹490" },
  { code: "CC0042", name: "Phosphoric Acid", category: "Acids", pack_size: "500ml", price: "₹280" },
  { code: "CC0043", name: "Potassium Dichromate", category: "Salts", pack_size: "250g", price: "₹310" },
  { code: "CC0044", name: "Potassium Hydroxide", category: "Bases", pack_size: "500g", price: "₹260" },
  { code: "CC0045", name: "Potassium Iodide", category: "Salts", pack_size: "100g", price: "₹560" },
  { code: "CC0046", name: "Potassium Permanganate", category: "Salts", pack_size: "250g", price: "₹310" },
  { code: "CC0047", name: "Silver Nitrate", category: "Salts", pack_size: "25g", price: "₹1800" },
  { code: "CC0048", name: "Sodium Bicarbonate", category: "Bases", pack_size: "500g", price: "₹90" },
  { code: "CC0049", name: "Sodium Carbonate", category: "Bases", pack_size: "500g", price: "₹120" },
  { code: "CC0050", name: "Sodium Hydroxide Pellets", category: "Bases", pack_size: "500g", price: "₹150" },
  { code: "CC0051", name: "Sodium Nitrate", category: "Salts", pack_size: "500g", price: "₹160" },
  { code: "CC0052", name: "Sodium Sulphate", category: "Salts", pack_size: "500g", price: "₹130" },
  { code: "CC0053", name: "Sulphuric Acid", category: "Acids", pack_size: "500ml", price: "₹110" },
  { code: "CC0054", name: "Toluene", category: "Solvents", pack_size: "1L", price: "₹420" },
  { code: "CC0055", name: "Trichloroethylene", category: "Solvents", pack_size: "500ml", price: "₹580" },
  { code: "CC0056", name: "Xylene", category: "Solvents", pack_size: "1L", price: "₹490" },
]

export const chemicalCategories = ["All", "Acids", "Solvents", "Bases", "Salts", "Reagents"]

export const labSupplyBrands = {
  qualigens: {
    name: "Qualigens",
    description: "High-quality laboratory chemicals and reagents",
    logo: "/images/logo-qualigens.png",
    categories: ["Analytical Reagents", "Solvents", "Acids & Bases", "Salts"],
  },
  borosil: {
    name: "Borosil",
    description: "Premium laboratory glassware and equipment",
    logo: "/images/logo-borosil.png",
    categories: ["Glassware", "Laboratory Equipment", "Measuring Instruments"],
  },
  whatman: {
    name: "Whatman",
    description: "Filtration and separation products",
    logo: "/images/logo-whatman.png",
    categories: ["Filter Papers", "Membranes", "Syringe Filters", "Separation Media"],
  },
  rankem: {
    name: "Rankem",
    description: "Analytical and laboratory chemicals",
    logo: "/images/logo-rankem.png",
    categories: ["Analytical Reagents", "HPLC Solvents", "Buffer Solutions"],
  },
  jtbaker: {
    name: "J.T. Baker",
    description: "High-purity chemicals and solvents",
    logo: "/images/logo-jtbaker.png",
    categories: ["HPLC Grade Solvents", "Analytical Reagents", "Acids", "Bases"],
  },
}
