export const commercialChemicals = [
  { code: "CC0001", name: "Acetic Acid Glacial", category: "Acids" },
  { code: "CC0002", name: "Acetone", category: "Solvents" },
  { code: "CC0003", name: "Acetonitrile", category: "Solvents" },
  { code: "CC0004", name: "Alum (Non Ferric/Ferric) – Stone/Powder", category: "Salts" },
  { code: "CC0005", name: "Ammonium Bi-Sulphite", category: "Salts" },
  { code: "CC0006", name: "Ammonium Chloride", category: "Salts" },
  { code: "CC0007", name: "Aniline", category: "Reagents" },
  { code: "CC0008", name: "Boric Acid Powder", category: "Acids" },
  { code: "CC0009", name: "Bleaching Powder", category: "Reagents" },
  { code: "CC0010", name: "Butyl Acetate", category: "Solvents" },
  { code: "CC0011", name: "Butyl Cellosolve", category: "Solvents" },
  { code: "CC0012", name: "Butyl Alcohol", category: "Solvents" },
  { code: "CC0013", name: "Cab-O-Sil (Silicon Dioxide)", category: "Reagents" },
  { code: "CC0014", name: "Calcium Chloride (Lumps/Brine/Powder)", category: "Salts" },
  { code: "CC0015", name: "Caustic Potash Flakes (Potassium Hydroxide)", category: "Bases" },
  { code: "CC0016", name: "Caustic Soda Flakes (Sodium Hydroxide)", category: "Bases" },
  { code: "CC0017", name: "Chloroform", category: "Solvents" },
  { code: "CC0018", name: "Copper Sulphate", category: "Salts" },
  { code: "CC0019", name: "Ethanol (Denatured)", category: "Solvents" },
  { code: "CC0020", name: "Formaldehyde Solution", category: "Reagents" },
  { code: "CC0021", name: "Glacial Acetic Acid", category: "Acids" },
  { code: "CC0022", name: "Hydrochloric Acid (35%)", category: "Acids" },
  { code: "CC0023", name: "Nitric Acid (70%)", category: "Acids" },
  { code: "CC0024", name: "Phosphoric Acid", category: "Acids" },
  { code: "CC0025", name: "Potassium Permanganate", category: "Reagents" },
  { code: "CC0026", name: "Sodium Carbonate", category: "Bases" },
  { code: "CC0027", name: "Sodium Chloride", category: "Salts" },
  { code: "CC0028", name: "Sulphuric Acid (98%)", category: "Acids" },
  { code: "CC0029", name: "Toluene", category: "Solvents" },
  { code: "CC0030", name: "Xylene", category: "Solvents" },
].map((p) => ({ ...p, pack_size: "TBD", price: "TBD" }))

export const chemicalCategories = ["All", "Acids", "Solvents", "Bases", "Salts", "Reagents"]

export const labSupplyBrands: Record<string, { name: string; categories: string[] }> = {
  "fisher-chemical": { name: "Fisher Chemical", categories: ["Lab Chemicals", "Reagents"] },
  reagecon: { name: "Reagecon", categories: ["Lab Chemicals", "Reagents"] },
  "thermo-scientific": { name: "Thermo Scientific", categories: ["Instruments", "Reagents"] },
  rankem: { name: "Rankem", categories: ["Lab Chemicals", "Solvents"] },
  "acros-organics": { name: "Acros Organics", categories: ["Lab Chemicals"] },
  remel: { name: "Remel", categories: ["Reagents"] },
  "fisher-bioreagents": { name: "Fisher BioReagents", categories: ["Reagents"] },
  jtbaker: { name: "J.T.Baker", categories: ["Lab Chemicals"] },
  decon: { name: "Decon", categories: ["Reagents"] },
  qualigens: { name: "Qualigens", categories: ["Lab Chemicals", "Solvents"] },
  microbiologics: { name: "MicroBioLogics", categories: ["Reagents"] },
  "kimberly-clark": { name: "Kimberly-Clark", categories: ["Consumables"] },
  riviera: { name: "Riviera", categories: ["Glassware"] },
  "em-techcolor": { name: "EM Techcolor", categories: ["Instruments"] },
  "duran-group": { name: "Duran Group", categories: ["Glassware"] },
  troemner: { name: "Troemner", categories: ["Instruments"] },
  johnsondiversey: { name: "JohnsonDiversey", categories: ["Reagents"] },
  oxoid: { name: "Oxoid", categories: ["Reagents"] },
  biotek: { name: "BioTek", categories: ["Instruments"] },
  corning: { name: "Corning", categories: ["Glassware", "Instruments"] },
  "plas-labs": { name: "Plas Labs", categories: ["Instruments"] },
  lonza: { name: "Lonza", categories: ["Reagents"] },
  dupont: { name: "DuPont", categories: ["Reagents", "Consumables"] },
  maybridge: { name: "Maybridge", categories: ["Reagents"] },
  labconco: { name: "Labconco", categories: ["Instruments"] },
  superlab: { name: "Superlab", categories: ["Glassware"] },
  ika: { name: "IKA", categories: ["Instruments"] },
  borosil: { name: "Borosil", categories: ["Glassware", "Instruments"] },
  whatman: { name: "Whatman", categories: ["Filter Papers"] },
  avarice: { name: "Avarice", categories: ["Instruments"] },
}
