export const qualigensProducts = [
  {
    id: "Q001",
    code: "Q001",
    name: "Acetic Acid Glacial",
    cas: "64-19-7",
    category: "Acids",
    packSize: "500ml",
    material: "Glass Bottle",
    price: 450,
    purity: "99.5%",
    brand: "Qualigens",
  },
  {
    id: "Q002",
    code: "Q002",
    name: "Acetone",
    cas: "67-64-1",
    category: "Solvents",
    packSize: "1L",
    material: "Glass Bottle",
    price: 320,
    purity: "99.5%",
    brand: "Qualigens",
  },
  {
    id: "Q003",
    code: "Q003",
    name: "Acetonitrile",
    cas: "75-05-8",
    category: "Solvents",
    packSize: "1L",
    material: "Glass Bottle",
    price: 850,
    purity: "99.9%",
    brand: "Qualigens",
  },
  {
    id: "Q004",
    code: "Q004",
    name: "Sulfuric Acid 98%",
    cas: "7664-93-9",
    category: "Acids",
    packSize: "500ml",
    material: "Glass Bottle",
    price: 280,
    purity: "98%",
    brand: "Qualigens",
  },
  {
    id: "Q005",
    code: "Q005",
    name: "Sodium Hydroxide Pellets",
    cas: "1310-73-2",
    category: "Bases",
    packSize: "500g",
    material: "Plastic Bottle",
    price: 180,
    purity: "99%",
    brand: "Qualigens",
  },
  {
    id: "Q006",
    code: "Q006",
    name: "Hydrochloric Acid 37%",
    cas: "7647-01-0",
    category: "Acids",
    packSize: "500ml",
    material: "Glass Bottle",
    price: 220,
    purity: "37%",
    brand: "Qualigens",
  },
  {
    id: "Q007",
    code: "Q007",
    name: "Methanol",
    cas: "67-56-1",
    category: "Solvents",
    packSize: "1L",
    material: "Glass Bottle",
    price: 380,
    purity: "99.8%",
    brand: "Qualigens",
  },
  {
    id: "Q008",
    code: "Q008",
    name: "Ethanol Absolute",
    cas: "64-17-5",
    category: "Solvents",
    packSize: "1L",
    material: "Glass Bottle",
    price: 420,
    purity: "99.9%",
    brand: "Qualigens",
  },
  {
    id: "Q009",
    code: "Q009",
    name: "Distilled Water",
    cas: "7732-18-5",
    category: "Solvents",
    packSize: "1L",
    material: "Plastic Bottle",
    price: 45,
    purity: "99.9%",
    brand: "Qualigens",
  },
  {
    id: "Q010",
    code: "Q010",
    name: "Toluene",
    cas: "108-88-3",
    category: "Solvents",
    packSize: "1L",
    material: "Glass Bottle",
    price: 350,
    purity: "99.5%",
    brand: "Qualigens",
  },
  {
    id: "Q011",
    code: "Q011",
    name: "Xylene",
    cas: "1330-20-7",
    category: "Solvents",
    packSize: "1L",
    material: "Glass Bottle",
    price: 380,
    purity: "99%",
    brand: "Qualigens",
  },
  {
    id: "Q012",
    code: "Q012",
    name: "Benzene",
    cas: "71-43-2",
    category: "Solvents",
    packSize: "500ml",
    material: "Glass Bottle",
    price: 450,
    purity: "99.5%",
    brand: "Qualigens",
  },
  {
    id: "Q013",
    code: "Q013",
    name: "Ethyl Acetate",
    cas: "141-78-6",
    category: "Solvents",
    packSize: "1L",
    material: "Glass Bottle",
    price: 320,
    purity: "99.5%",
    brand: "Qualigens",
  },
  {
    id: "Q014",
    code: "Q014",
    name: "Methyl Ethyl Ketone",
    cas: "78-93-3",
    category: "Solvents",
    packSize: "1L",
    material: "Glass Bottle",
    price: 380,
    purity: "99%",
    brand: "Qualigens",
  },
  {
    id: "Q015",
    code: "Q015",
    name: "Chloroform",
    cas: "67-66-3",
    category: "Solvents",
    packSize: "500ml",
    material: "Glass Bottle",
    price: 420,
    purity: "99%",
    brand: "Qualigens",
  },
  {
    id: "Q016",
    code: "Q016",
    name: "Dichloromethane",
    cas: "75-09-2",
    category: "Solvents",
    packSize: "1L",
    material: "Glass Bottle",
    price: 480,
    purity: "99.5%",
    brand: "Qualigens",
  },
  {
    id: "Q017",
    code: "Q017",
    name: "Tetrahydrofuran",
    cas: "109-99-9",
    category: "Solvents",
    packSize: "1L",
    material: "Glass Bottle",
    price: 650,
    purity: "99.5%",
    brand: "Qualigens",
  },
  {
    id: "Q018",
    code: "Q018",
    name: "Dimethylformamide",
    cas: "68-12-2",
    category: "Solvents",
    packSize: "1L",
    material: "Glass Bottle",
    price: 520,
    purity: "99.8%",
    brand: "Qualigens",
  },
  {
    id: "Q019",
    code: "Q019",
    name: "Dimethyl Sulfoxide",
    cas: "67-68-5",
    category: "Solvents",
    packSize: "500ml",
    material: "Glass Bottle",
    price: 380,
    purity: "99.9%",
    brand: "Qualigens",
  },
  {
    id: "Q020",
    code: "Q020",
    name: "n-Hexane",
    cas: "110-54-3",
    category: "Solvents",
    packSize: "1L",
    material: "Glass Bottle",
    price: 420,
    purity: "99%",
    brand: "Qualigens",
  },
]

export default qualigensProducts
